/*
 * Visier Data Intake APIs
 * Visier APIs for sending raw or untransformed source data to Visier
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DataTransferResultDetail;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PushDataCompleteResponse
 */
public class PushDataCompleteResponseTest {
    private final PushDataCompleteResponse model = new PushDataCompleteResponse();

    /**
     * Model tests for PushDataCompleteResponse
     */
    @Test
    public void testPushDataCompleteResponse() {
        // TODO: test PushDataCompleteResponse
    }

    /**
     * Test the property 'dataReceivingJobId'
     */
    @Test
    public void dataReceivingJobIdTest() {
        // TODO: test dataReceivingJobId
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'transferSessionId'
     */
    @Test
    public void transferSessionIdTest() {
        // TODO: test transferSessionId
    }

    /**
     * Test the property 'dataTransferResultDetails'
     */
    @Test
    public void dataTransferResultDetailsTest() {
        // TODO: test dataTransferResultDetails
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
