/*
 * Visier Data Intake APIs
 * Visier APIs for sending raw or untransformed source data to Visier
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PushDataColumnDefinitionDTO
 */
public class PushDataColumnDefinitionDTOTest {
    private final PushDataColumnDefinitionDTO model = new PushDataColumnDefinitionDTO();

    /**
     * Model tests for PushDataColumnDefinitionDTO
     */
    @Test
    public void testPushDataColumnDefinitionDTO() {
        // TODO: test PushDataColumnDefinitionDTO
    }

    /**
     * Test the property 'columnName'
     */
    @Test
    public void columnNameTest() {
        // TODO: test columnName
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'dataFormats'
     */
    @Test
    public void dataFormatsTest() {
        // TODO: test dataFormats
    }

    /**
     * Test the property 'isMandatory'
     */
    @Test
    public void isMandatoryTest() {
        // TODO: test isMandatory
    }

    /**
     * Test the property 'allowEmpty'
     */
    @Test
    public void allowEmptyTest() {
        // TODO: test allowEmpty
    }

    /**
     * Test the property 'defaultValue'
     */
    @Test
    public void defaultValueTest() {
        // TODO: test defaultValue
    }

}
