/*
 * Visier Data Intake APIs
 * Visier APIs for sending raw or untransformed source data to Visier
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PushDataCompleteRequest
 */
public class PushDataCompleteRequestTest {
    private final PushDataCompleteRequest model = new PushDataCompleteRequest();

    /**
     * Model tests for PushDataCompleteRequest
     */
    @Test
    public void testPushDataCompleteRequest() {
        // TODO: test PushDataCompleteRequest
    }

    /**
     * Test the property 'transferSessionId'
     */
    @Test
    public void transferSessionIdTest() {
        // TODO: test transferSessionId
    }

    /**
     * Test the property 'processingData'
     */
    @Test
    public void processingDataTest() {
        // TODO: test processingData
    }

}
