/*
 * Visier Data Intake APIs
 * Visier APIs for sending raw or untransformed source data to Visier
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Job;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReceivingJobStatusResponse
 */
public class ReceivingJobStatusResponseTest {
    private final ReceivingJobStatusResponse model = new ReceivingJobStatusResponse();

    /**
     * Model tests for ReceivingJobStatusResponse
     */
    @Test
    public void testReceivingJobStatusResponse() {
        // TODO: test ReceivingJobStatusResponse
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    public void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'parentJobId'
     */
    @Test
    public void parentJobIdTest() {
        // TODO: test parentJobId
    }

    /**
     * Test the property 'parentTenantCode'
     */
    @Test
    public void parentTenantCodeTest() {
        // TODO: test parentTenantCode
    }

    /**
     * Test the property 'receivingJobs'
     */
    @Test
    public void receivingJobsTest() {
        // TODO: test receivingJobs
    }

}
