/*
 * Visier Data Intake APIs
 * Visier APIs for sending raw or untransformed source data to Visier
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DataTransferResultDetail;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PushDataCompleteResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PushDataCompleteResponse {
  public static final String SERIALIZED_NAME_DATA_RECEIVING_JOB_ID = "dataReceivingJobId";
  @SerializedName(SERIALIZED_NAME_DATA_RECEIVING_JOB_ID)
  private String dataReceivingJobId;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_TRANSFER_SESSION_ID = "transferSessionId";
  @SerializedName(SERIALIZED_NAME_TRANSFER_SESSION_ID)
  private String transferSessionId;

  public static final String SERIALIZED_NAME_DATA_TRANSFER_RESULT_DETAILS = "dataTransferResultDetails";
  @SerializedName(SERIALIZED_NAME_DATA_TRANSFER_RESULT_DETAILS)
  private List<DataTransferResultDetail> dataTransferResultDetails = null;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public PushDataCompleteResponse() {
  }

  public PushDataCompleteResponse dataReceivingJobId(String dataReceivingJobId) {
    
    
    
    
    this.dataReceivingJobId = dataReceivingJobId;
    return this;
  }

   /**
   * The unique identifier associated with the receiving job.
   * @return dataReceivingJobId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique identifier associated with the receiving job.")

  public String getDataReceivingJobId() {
    return dataReceivingJobId;
  }


  public void setDataReceivingJobId(String dataReceivingJobId) {
    
    
    
    this.dataReceivingJobId = dataReceivingJobId;
  }


  public PushDataCompleteResponse message(String message) {
    
    
    
    
    this.message = message;
    return this;
  }

   /**
   * A meaningful message about the transfer session.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A meaningful message about the transfer session.")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    
    
    
    this.message = message;
  }


  public PushDataCompleteResponse transferSessionId(String transferSessionId) {
    
    
    
    
    this.transferSessionId = transferSessionId;
    return this;
  }

   /**
   * The unique identifier associated with the transfer session.
   * @return transferSessionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique identifier associated with the transfer session.")

  public String getTransferSessionId() {
    return transferSessionId;
  }


  public void setTransferSessionId(String transferSessionId) {
    
    
    
    this.transferSessionId = transferSessionId;
  }


  public PushDataCompleteResponse dataTransferResultDetails(List<DataTransferResultDetail> dataTransferResultDetails) {
    
    
    
    
    this.dataTransferResultDetails = dataTransferResultDetails;
    return this;
  }

  public PushDataCompleteResponse addDataTransferResultDetailsItem(DataTransferResultDetail dataTransferResultDetailsItem) {
    if (this.dataTransferResultDetails == null) {
      this.dataTransferResultDetails = new ArrayList<>();
    }
    this.dataTransferResultDetails.add(dataTransferResultDetailsItem);
    return this;
  }

   /**
   * A list of objects representing the results of the transfer session.
   * @return dataTransferResultDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of objects representing the results of the transfer session.")

  public List<DataTransferResultDetail> getDataTransferResultDetails() {
    return dataTransferResultDetails;
  }


  public void setDataTransferResultDetails(List<DataTransferResultDetail> dataTransferResultDetails) {
    
    
    
    this.dataTransferResultDetails = dataTransferResultDetails;
  }


  public PushDataCompleteResponse status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * The status of the transfer session. A completed session returns the status SUCCEED.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The status of the transfer session. A completed session returns the status SUCCEED.")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PushDataCompleteResponse instance itself
   */
  public PushDataCompleteResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PushDataCompleteResponse pushDataCompleteResponse = (PushDataCompleteResponse) o;
    return Objects.equals(this.dataReceivingJobId, pushDataCompleteResponse.dataReceivingJobId) &&
        Objects.equals(this.message, pushDataCompleteResponse.message) &&
        Objects.equals(this.transferSessionId, pushDataCompleteResponse.transferSessionId) &&
        Objects.equals(this.dataTransferResultDetails, pushDataCompleteResponse.dataTransferResultDetails) &&
        Objects.equals(this.status, pushDataCompleteResponse.status)&&
        Objects.equals(this.additionalProperties, pushDataCompleteResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataReceivingJobId, message, transferSessionId, dataTransferResultDetails, status, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PushDataCompleteResponse {\n");
    sb.append("    dataReceivingJobId: ").append(toIndentedString(dataReceivingJobId)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    transferSessionId: ").append(toIndentedString(transferSessionId)).append("\n");
    sb.append("    dataTransferResultDetails: ").append(toIndentedString(dataTransferResultDetails)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("dataReceivingJobId");
    openapiFields.add("message");
    openapiFields.add("transferSessionId");
    openapiFields.add("dataTransferResultDetails");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PushDataCompleteResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PushDataCompleteResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PushDataCompleteResponse is not found in the empty JSON string", PushDataCompleteResponse.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("dataReceivingJobId") != null && !jsonObj.get("dataReceivingJobId").isJsonNull()) && !jsonObj.get("dataReceivingJobId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dataReceivingJobId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataReceivingJobId").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      if ((jsonObj.get("transferSessionId") != null && !jsonObj.get("transferSessionId").isJsonNull()) && !jsonObj.get("transferSessionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transferSessionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transferSessionId").toString()));
      }
      if (jsonObj.get("dataTransferResultDetails") != null && !jsonObj.get("dataTransferResultDetails").isJsonNull()) {
        JsonArray jsonArraydataTransferResultDetails = jsonObj.getAsJsonArray("dataTransferResultDetails");
        if (jsonArraydataTransferResultDetails != null) {
          // ensure the json data is an array
          if (!jsonObj.get("dataTransferResultDetails").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `dataTransferResultDetails` to be an array in the JSON string but got `%s`", jsonObj.get("dataTransferResultDetails").toString()));
          }

          // validate the optional field `dataTransferResultDetails` (array)
          for (int i = 0; i < jsonArraydataTransferResultDetails.size(); i++) {
            DataTransferResultDetail.validateJsonObject(jsonArraydataTransferResultDetails.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PushDataCompleteResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PushDataCompleteResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PushDataCompleteResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PushDataCompleteResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<PushDataCompleteResponse>() {
           @Override
           public void write(JsonWriter out, PushDataCompleteResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PushDataCompleteResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PushDataCompleteResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PushDataCompleteResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PushDataCompleteResponse
  * @throws IOException if the JSON string is invalid with respect to PushDataCompleteResponse
  */
  public static PushDataCompleteResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PushDataCompleteResponse.class);
  }

 /**
  * Convert an instance of PushDataCompleteResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

