/*
 * Visier Data Intake APIs
 * Visier APIs for sending raw or untransformed source data to Visier
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Definition of the source column.
 */
@ApiModel(description = "Definition of the source column.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PushDataColumnDefinitionDTO {
  public static final String SERIALIZED_NAME_COLUMN_NAME = "columnName";
  @SerializedName(SERIALIZED_NAME_COLUMN_NAME)
  private String columnName;

  public static final String SERIALIZED_NAME_DATA_TYPE = "dataType";
  @SerializedName(SERIALIZED_NAME_DATA_TYPE)
  private String dataType;

  public static final String SERIALIZED_NAME_DATA_FORMATS = "dataFormats";
  @SerializedName(SERIALIZED_NAME_DATA_FORMATS)
  private List<String> dataFormats = null;

  public static final String SERIALIZED_NAME_IS_MANDATORY = "isMandatory";
  @SerializedName(SERIALIZED_NAME_IS_MANDATORY)
  private Boolean isMandatory;

  public static final String SERIALIZED_NAME_ALLOW_EMPTY = "allowEmpty";
  @SerializedName(SERIALIZED_NAME_ALLOW_EMPTY)
  private Boolean allowEmpty;

  public static final String SERIALIZED_NAME_DEFAULT_VALUE = "defaultValue";
  @SerializedName(SERIALIZED_NAME_DEFAULT_VALUE)
  private String defaultValue;

  public PushDataColumnDefinitionDTO() {
  }

  public PushDataColumnDefinitionDTO columnName(String columnName) {
    
    
    
    
    this.columnName = columnName;
    return this;
  }

   /**
   * The name of the column.
   * @return columnName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the column.")

  public String getColumnName() {
    return columnName;
  }


  public void setColumnName(String columnName) {
    
    
    
    this.columnName = columnName;
  }


  public PushDataColumnDefinitionDTO dataType(String dataType) {
    
    
    
    
    this.dataType = dataType;
    return this;
  }

   /**
   * The data type associated with the column.
   * @return dataType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The data type associated with the column.")

  public String getDataType() {
    return dataType;
  }


  public void setDataType(String dataType) {
    
    
    
    this.dataType = dataType;
  }


  public PushDataColumnDefinitionDTO dataFormats(List<String> dataFormats) {
    
    
    
    
    this.dataFormats = dataFormats;
    return this;
  }

  public PushDataColumnDefinitionDTO addDataFormatsItem(String dataFormatsItem) {
    if (this.dataFormats == null) {
      this.dataFormats = new ArrayList<>();
    }
    this.dataFormats.add(dataFormatsItem);
    return this;
  }

   /**
   * The expected format for datetime data types.
   * @return dataFormats
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The expected format for datetime data types.")

  public List<String> getDataFormats() {
    return dataFormats;
  }


  public void setDataFormats(List<String> dataFormats) {
    
    
    
    this.dataFormats = dataFormats;
  }


  public PushDataColumnDefinitionDTO isMandatory(Boolean isMandatory) {
    
    
    
    
    this.isMandatory = isMandatory;
    return this;
  }

   /**
   * If true, the column value is required. If a column is mandatory, and the file is missing this column, the request will fail.
   * @return isMandatory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If true, the column value is required. If a column is mandatory, and the file is missing this column, the request will fail.")

  public Boolean getIsMandatory() {
    return isMandatory;
  }


  public void setIsMandatory(Boolean isMandatory) {
    
    
    
    this.isMandatory = isMandatory;
  }


  public PushDataColumnDefinitionDTO allowEmpty(Boolean allowEmpty) {
    
    
    
    
    this.allowEmpty = allowEmpty;
    return this;
  }

   /**
   * If true, the column allows an empty value for the record.
   * @return allowEmpty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If true, the column allows an empty value for the record.")

  public Boolean getAllowEmpty() {
    return allowEmpty;
  }


  public void setAllowEmpty(Boolean allowEmpty) {
    
    
    
    this.allowEmpty = allowEmpty;
  }


  public PushDataColumnDefinitionDTO defaultValue(String defaultValue) {
    
    
    
    
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * The default value of the column.
   * @return defaultValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The default value of the column.")

  public String getDefaultValue() {
    return defaultValue;
  }


  public void setDefaultValue(String defaultValue) {
    
    
    
    this.defaultValue = defaultValue;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PushDataColumnDefinitionDTO instance itself
   */
  public PushDataColumnDefinitionDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PushDataColumnDefinitionDTO pushDataColumnDefinitionDTO = (PushDataColumnDefinitionDTO) o;
    return Objects.equals(this.columnName, pushDataColumnDefinitionDTO.columnName) &&
        Objects.equals(this.dataType, pushDataColumnDefinitionDTO.dataType) &&
        Objects.equals(this.dataFormats, pushDataColumnDefinitionDTO.dataFormats) &&
        Objects.equals(this.isMandatory, pushDataColumnDefinitionDTO.isMandatory) &&
        Objects.equals(this.allowEmpty, pushDataColumnDefinitionDTO.allowEmpty) &&
        Objects.equals(this.defaultValue, pushDataColumnDefinitionDTO.defaultValue)&&
        Objects.equals(this.additionalProperties, pushDataColumnDefinitionDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columnName, dataType, dataFormats, isMandatory, allowEmpty, defaultValue, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PushDataColumnDefinitionDTO {\n");
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("    dataFormats: ").append(toIndentedString(dataFormats)).append("\n");
    sb.append("    isMandatory: ").append(toIndentedString(isMandatory)).append("\n");
    sb.append("    allowEmpty: ").append(toIndentedString(allowEmpty)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("columnName");
    openapiFields.add("dataType");
    openapiFields.add("dataFormats");
    openapiFields.add("isMandatory");
    openapiFields.add("allowEmpty");
    openapiFields.add("defaultValue");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PushDataColumnDefinitionDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PushDataColumnDefinitionDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PushDataColumnDefinitionDTO is not found in the empty JSON string", PushDataColumnDefinitionDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("columnName") != null && !jsonObj.get("columnName").isJsonNull()) && !jsonObj.get("columnName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `columnName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("columnName").toString()));
      }
      if ((jsonObj.get("dataType") != null && !jsonObj.get("dataType").isJsonNull()) && !jsonObj.get("dataType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dataType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataType").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("dataFormats") != null && !jsonObj.get("dataFormats").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `dataFormats` to be an array in the JSON string but got `%s`", jsonObj.get("dataFormats").toString()));
      }
      if ((jsonObj.get("defaultValue") != null && !jsonObj.get("defaultValue").isJsonNull()) && !jsonObj.get("defaultValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `defaultValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("defaultValue").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PushDataColumnDefinitionDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PushDataColumnDefinitionDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PushDataColumnDefinitionDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PushDataColumnDefinitionDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<PushDataColumnDefinitionDTO>() {
           @Override
           public void write(JsonWriter out, PushDataColumnDefinitionDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PushDataColumnDefinitionDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PushDataColumnDefinitionDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PushDataColumnDefinitionDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PushDataColumnDefinitionDTO
  * @throws IOException if the JSON string is invalid with respect to PushDataColumnDefinitionDTO
  */
  public static PushDataColumnDefinitionDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PushDataColumnDefinitionDTO.class);
  }

 /**
  * Convert an instance of PushDataColumnDefinitionDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

